"""
Django settings for visitsikkim_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
# import os
# from pathlib import Path
# from decouple import config
# # settings.py

# from dotenv import load_dotenv

# # Load the .env file
# load_dotenv()

# # Now you can read the secret key
# GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-5%a-$h6ld&qrfmz^c-(*gp%^4isrgdzn$xrdn12+6e+dh9nqni'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#      'main',

# ]

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# ROOT_URLCONF = 'visitsikkim_project.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#        'DIRS': [BASE_DIR / 'templates'],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'visitsikkim_project.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',
# #     }
# # }


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'railway',
#         'USER': 'postgres',
#         'PASSWORD': 'PHLBEuNBwWmrDBIdMyBPTYiGSetLTvoE',
#         'HOST': 'postgres.railway.internal',
#         'PORT': '5432',
#     }
# }



# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
# ]

# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / "media"

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# 



# import os
# from pathlib import Path
# import dj_database_url
# from decouple import config 
# from dotenv import load_dotenv
#  # python-decouple will automatically read .env
# load_dotenv()

# # Build paths inside the project
# BASE_DIR = Path(__file__).resolve().parent.parent

# # Secret key & API keys
# SECRET_KEY = config("SECRET_KEY", default="django-insecure-CHANGE_ME")  # optional fallback
# GEMINI_API_KEY = config("GEMINI_API_KEY", default="")

# # SECURITY WARNING: don’t run with debug turned on in production!
# DEBUG = config("DEBUG", default=True, cast=bool)

# # Railway requires your domain or * during development
# ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="*").split(",")

# # Application definition
# INSTALLED_APPS = [
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",
#     "main",
# ]

# MIDDLEWARE = [
#     "django.middleware.security.SecurityMiddleware",
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]

# ROOT_URLCONF = "visitsikkim_project.urls"

# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [BASE_DIR / "templates"],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = "visitsikkim_project.wsgi.application"

# # ✅ Database (Railway PostgreSQL)
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',
# #     }
# # }
# DATABASE_URL = os.getenv('DATABASE_URL')
# if DATABASE_URL:
#     db_from_env = dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)
#     DATABASES['default'].update(db_from_env)

# DATABASE_URL = os.getenv('DATABASE_URL')
# if DATABASE_URL:
#     DATABASES['default'] = dj_database_url.parse(DATABASE_URL)

#  DATABASES['default'] = dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)
# # Password validation
# AUTH_PASSWORD_VALIDATORS = [
#     {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
#     {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
#     {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
#     {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
# ]

# # Internationalization
# LANGUAGE_CODE = "en-us"
# TIME_ZONE = "UTC"
# USE_I18N = True
# USE_TZ = True

# # Static & Media files
# STATIC_URL = "/static/"
# STATICFILES_DIRS = [BASE_DIR / "static"]

# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"

# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# import os
# from pathlib import Path
# import dj_database_url
# from decouple import config
# from dotenv import load_dotenv

# # Load .env variables
# load_dotenv()

# # Build paths inside the project
# BASE_DIR = Path(__file__).resolve().parent.parent

# # Secret key & API keys
# SECRET_KEY = config("SECRET_KEY", default="django-insecure-CHANGE_ME")
# GEMINI_API_KEY = config("GEMINI_API_KEY", default="")

# # SECURITY WARNING: don’t run with debug turned on in production!
# DEBUG = config("DEBUG", default=True, cast=bool)

# # Railway requires your domain or * during development
# ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="*").split(",")

# # Application definition
# INSTALLED_APPS = [
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",
#     "main",
# ]

# MIDDLEWARE = [
#     "django.middleware.security.SecurityMiddleware",
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]

# ROOT_URLCONF = "visitsikkim_project.urls"

# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [BASE_DIR / "templates"],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = "visitsikkim_project.wsgi.application"

# # ------------------------
# # Database configuration
# # ------------------------

# # Default: SQLite (local development)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# # Override with Railway PostgreSQL if DATABASE_URL exists
# DATABASE_URL = os.getenv('DATABASE_URL')
# if DATABASE_URL:
#     db_from_env = dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)
#     DATABASES['default'].update(db_from_env)

# # ------------------------
# # Password validation
# # ------------------------
# AUTH_PASSWORD_VALIDATORS = [
#     {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
#     {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
#     {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
#     {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
# ]

# # ------------------------
# # Internationalization
# # ------------------------
# LANGUAGE_CODE = "en-us"
# TIME_ZONE = "UTC"
# USE_I18N = True
# USE_TZ = True

# # ------------------------
# # Static & Media files
# # ------------------------
# STATIC_URL = "/static/"
# STATICFILES_DIRS = [BASE_DIR / "static"]

# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"

# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# # import os
# # from pathlib import Path
# # import dj_database_url
# # from decouple import config
# # from dotenv import load_dotenv

# # # ------------------------
# # # Load environment variables
# # # ------------------------
# # load_dotenv()

# # # ------------------------
# # # Base Directory
# # # ------------------------
# # BASE_DIR = Path(__file__).resolve().parent.parent

# # # ------------------------
# # # Secret Keys & API Keys
# # # ------------------------
# # SECRET_KEY = config("SECRET_KEY", default="django-insecure-CHANGE_ME")
# # GEMINI_API_KEY = config("GEMINI_API_KEY", default="")

# # # ------------------------
# # # Debug Mode
# # # ------------------------
# # DEBUG = config("DEBUG", default=True, cast=bool)

# # ------------------------
# # Allowed Hosts
# # ------------------------
# ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="*").split(",")

# # ------------------------
# # Installed Apps
# # ------------------------
# INSTALLED_APPS = [
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",
#     "main",  # Your main app
# ]

# # ------------------------
# # Middleware
# # ------------------------
# MIDDLEWARE = [
#     "django.middleware.security.SecurityMiddleware",
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]

# ROOT_URLCONF = "visitsikkim_project.urls"

# # ------------------------
# # Templates
# # ------------------------
# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [BASE_DIR / "templates"],  # Custom templates folder
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.debug",
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = "visitsikkim_project.wsgi.application"

# # ------------------------
# # Database Configuration
# # ------------------------
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",  # Default for local dev
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

# # Use Railway PostgreSQL if DATABASE_URL exists
# # DATABASE_URL = os.getenv("DATABASE_URL")
# # if DATABASE_URL:
# #     DATABASES["default"] = dj_database_url.parse(
# #         DATABASE_URL,
# #         conn_max_age=600,
# #         ssl_require=True
        
# #     )      
# DATABASE_URL = os.getenv("DATABASE_URL")
# if DATABASE_URL:
#     db_from_env = dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)
#     DATABASES["default"].update(db_from_env)
    

# # ------------------------
# # Password Validation
# # ------------------------
# AUTH_PASSWORD_VALIDATORS = [
#     {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
#     {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
#     {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
#     {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
# ]

# # ------------------------
# # Internationalization
# # ------------------------
# LANGUAGE_CODE = "en-us"
# TIME_ZONE = "Asia/Kolkata"  # More accurate for India users
# USE_I18N = True
# USE_TZ = True

# # ------------------------
# # Static & Media Files
# # ------------------------
# STATIC_URL = "/static/"
# STATICFILES_DIRS = [BASE_DIR / "static"]
# STATIC_ROOT = BASE_DIR / "staticfiles"  # Important for production (collectstatic)

# MEDIA_URL = "/media/"
# MEDIA_ROOT = BASE_DIR / "media"

# # ------------------------
# # Default Primary Key
# # ------------------------
# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
import os
from pathlib import Path
import dj_database_url
from decouple import config
from dotenv import load_dotenv

# Load .env variables
load_dotenv()

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# Secret key & API keys
SECRET_KEY = config("SECRET_KEY", default="django-insecure-CHANGE_ME")
GEMINI_API_KEY = config("GEMINI_API_KEY", default="")

# SECURITY WARNING: don’t run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

# Railway requires your domain or * during development
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="*").split(",")

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "visitsikkim_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "visitsikkim_project.wsgi.application"

# ------------------------
# Database configuration
# ------------------------

# Default: SQLite (local development)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Override with Railway PostgreSQL if DATABASE_URL exists
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    db_from_env = dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=True)
    DATABASES['default'].update(db_from_env)

# ------------------------
# Password validation
# ------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ------------------------
# Internationalization
# ------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ------------------------
# Static & Media files
# ------------------------
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"                       